const file = (path: string) => `${import.meta.env.BASE_URL}${path.replace(/^\//, "")}`;

export const ob = {
  logo: file("/assets/outbound/plot-logo.png"),
  avatar: file("/assets/outbound/avatar-shaahana.png"),
  brandMark: file("/assets/outbound/brand-mark.png"),
  rey: file("/assets/outbound/avatar-rey.jpg"),
  commentPhoto: file("/assets/outbound/comment-photo.png"),
  thumbs: [
    file("/assets/outbound/thumb-1.jpg"),
    file("/assets/outbound/thumb-2.jpg"),
    file("/assets/outbound/thumb-3.jpg"),
    file("/assets/outbound/thumb-4.jpg"),
    file("/assets/outbound/thumb-5.jpg"),
    file("/assets/outbound/thumb-6.jpg"),
    file("/assets/outbound/thumb-7.jpg"),
    file("/assets/outbound/thumb-8.jpg"),
  ],
  leadPosts: [
    file("/assets/outbound/lead-post-1.jpg"),
    file("/assets/outbound/lead-post-2.jpg"),
    file("/assets/outbound/lead-post-3.jpg"),
  ],
  orgCaret: file("/assets/outbound/icon-org-caret.svg"),
  collapse: file("/assets/outbound/icon-collapse.svg"),
  notifications: file("/assets/outbound/icon-notifications.svg"),
  chat: file("/assets/outbound/icon-chat.svg"),
  workflows: file("/assets/outbound/icon-workflows.svg"),
  home: file("/assets/outbound/icon-home.svg"),
  engagement: file("/assets/outbound/icon-engagement.svg"),
  brandAnalytics: file("/assets/outbound/icon-brand-analytics.svg"),
  chevron: file("/assets/outbound/icon-chevron.svg"),
  competitor: file("/assets/outbound/icon-competitor.svg"),
  outbound: file("/assets/outbound/icon-outbound.svg"),
  community: file("/assets/outbound/icon-community.svg"),
  sourcing: file("/assets/outbound/icon-sourcing.svg"),
  customReport: file("/assets/outbound/icon-custom-report.svg"),
  trends: file("/assets/outbound/icon-trends.svg"),
  juicebox: file("/assets/outbound/icon-juicebox.svg"),
  juiceboxCaret: file("/assets/outbound/icon-juicebox-caret.svg"),
  research: file("/assets/outbound/icon-research.svg"),
  bookmarks: file("/assets/outbound/icon-bookmarks.svg"),
  settings: file("/assets/outbound/icon-settings.svg"),
  more: file("/assets/outbound/icon-more.svg"),
  back: file("/assets/outbound/icon-back.svg"),
  invite: file("/assets/outbound/icon-invite.svg"),
  overflow: file("/assets/outbound/icon-overflow.svg"),
  sparkle: file("/assets/outbound/icon-sparkle.svg"),
  doodleBolt: file("/assets/outbound/doodle-bolt.svg"),
  doodleBurst: file("/assets/outbound/doodle-burst.svg"),
  info: file("/assets/outbound/icon-info.svg"),
  infoSm: file("/assets/outbound/icon-info-sm.svg"),
  heart: file("/assets/outbound/icon-heart.svg"),
  reply: file("/assets/outbound/icon-reply.svg"),
  impressions: file("/assets/outbound/icon-impressions.svg"),
  emv: file("/assets/outbound/icon-emv.svg"),
  refresh: file("/assets/outbound/icon-refresh.svg"),
  filter: file("/assets/outbound/icon-filter.svg"),
  caret: file("/assets/outbound/icon-caret.svg"),
  commentors: file("/assets/outbound/icon-commentors.svg"),
  platforms: file("/assets/outbound/icon-platforms.svg"),
  calendar: file("/assets/outbound/icon-calendar.svg"),
  gear: file("/assets/outbound/icon-gear.svg"),
  link: file("/assets/outbound/icon-link.svg"),
  sort: file("/assets/outbound/icon-sort.svg"),
  export: file("/assets/outbound/icon-export.svg"),
  grid: file("/assets/outbound/icon-grid.svg"),
  list: file("/assets/outbound/icon-list.svg"),
  search: file("/assets/outbound/icon-search.svg"),
  addPlus: file("/assets/outbound/icon-add-plus.svg"),
  metricHeart: file("/assets/outbound/icon-metric-heart.svg"),
  metricReply: file("/assets/outbound/icon-metric-reply.svg"),
  metricEye: file("/assets/outbound/icon-metric-eye.svg"),
  status: file("/assets/outbound/icon-status.svg"),
  topics: file("/assets/outbound/icon-topics.svg"),
  sortCol: file("/assets/outbound/icon-sort-col.svg"),
  scoreInfo: file("/assets/outbound/icon-score-info.svg"),
};
